version: '3'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pseudo_db
    volumes:
      - ./db/sql/:/docker-entrypoint-initdb.d/
  app:
    build: .
    ports:
      - "8080:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=admin
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_NAME=pseudo_db